service: vue-portfolio-frontend
image: arekusandoru/vue-portfolio-frontend

servers:
  web:
    - 165.227.200.55

proxy:
  ssl: true
  host: alexmuresan.dev
  healthcheck:
    path: /

registry:
  username: arekusandoru
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

ssh:
  user: root
  keys:
    - ~/.ssh/digitalocean
